#!/usr/bin/env node
// Pure-Node Cloudflare Workers deploy for Trailhead (PAYPAL-P2-WORKER-PORT-1,
// plan §3). No wrangler, no npm: the REST API via fetch. Idempotent — rerunning
// reuses the D1 database and overwrites the same script.
//
// Blast radius, fenced per the row + adversarial review:
//   - ensures exactly ONE D1 database (trailhead-db): POST, reuse on "exists"
//     via a name-filtered read of that one database
//   - PUTs exactly ONE worker script: {WORKER_NAME} from .env — never lists,
//     modifies or deletes any other script
//   - enables the workers.dev subdomain for that one script
//   - nothing else: no zone, route or nameserver operations (the B2 token
//     cannot anyway — scopes are Workers-Scripts:Edit + D1:Edit only)
//
// Secrets ride .env -> secret_text bindings at deploy time; values are never
// logged. Usage: node deploy/deploy-worker.mjs
import { readFileSync, readdirSync, mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = new URL('..', import.meta.url);
const D1_NAME = 'trailhead-db';
const SECRETS = ['PAYPAL_CLIENT_ID', 'PAYPAL_CLIENT_SECRET', 'LLM_BASE_URL', 'LLM_API_KEY', 'LLM_MODEL', 'MCP_TOKEN'];

const env = Object.fromEntries(
  readFileSync(new URL('../.env', import.meta.url), 'utf8')
    .split(/\r?\n/)
    .filter((l) => l.includes('=') && !l.trim().startsWith('#'))
    .map((l) => [l.slice(0, l.indexOf('=')).trim(), l.slice(l.indexOf('=') + 1).trim()])
    .filter(([, v]) => v !== '')
);

const missing = ['CF_API_TOKEN', 'CF_ACCOUNT_ID', 'WORKER_NAME', ...SECRETS].filter((k) => !env[k]);
if (missing.length) {
  console.error(`ABORT: missing required .env keys (values are never printed): ${missing.join(', ')}`);
  process.exit(1);
}
const WORKER_NAME = env.WORKER_NAME;
const acct = env.CF_ACCOUNT_ID;
const log = (m) => console.log(`deploy: ${m}`);

const api = async (method, path, body) => {
  const r = await fetch(`https://api.cloudflare.com/client/v4${path}`, {
    method,
    headers: {
      Authorization: `Bearer ${env.CF_API_TOKEN}`,
      ...(body && !(body instanceof FormData) ? { 'Content-Type': 'application/json' } : {}),
    },
    body: body === undefined ? undefined : body instanceof FormData ? body : JSON.stringify(body),
  });
  const j = await r.json().catch(() => ({ success: false, errors: [{ code: 0, message: `non-JSON response ${r.status}` }] }));
  if (!j.success) throw new Error(`${method} ${path} -> ${r.status}: ${(j.errors || []).map((e) => `${e.code} ${e.message}`).join('; ')}`);
  return j.result;
};

// 1. ensure the D1 database (create; on "exists", read back exactly this one by name)
let d1;
try {
  d1 = await api('POST', `/accounts/${acct}/d1/database`, { name: D1_NAME });
  log(`d1: created ${D1_NAME} (${d1.uuid})`);
} catch (e) {
  if (!/already exists/i.test(e.message)) throw e;
  const found = await api('GET', `/accounts/${acct}/d1/database?name=${D1_NAME}`);
  d1 = Array.isArray(found) ? found[0] : found;
  if (!d1?.uuid) throw new Error(`d1 ${D1_NAME} reported as existing but the name-filtered read returned nothing`);
  log(`d1: reusing ${D1_NAME} (${d1.uuid})`);
}

// 2. generate the assets module: public/* + the catalog, inlined for the Worker
const tmpDir = join(fileURLToPathSafe(), '.deploy-tmp');
mkdirSync(tmpDir, { recursive: true });
const assets = {};
for (const f of readdirSync(new URL('../public', import.meta.url), { withFileTypes: true })) {
  if (f.isFile()) assets[f.name] = readFileSync(new URL(`../public/${f.name}`, import.meta.url), 'utf8');
}
const catalogJson = readFileSync(new URL('../data/catalog.json', import.meta.url), 'utf8');
const assetsModule = `// GENERATED by deploy/deploy-worker.mjs at deploy time — do not edit or commit.
export const ASSETS = ${JSON.stringify(assets)};

export const CATALOG = ${catalogJson};
`;
const assetsPath = join(tmpDir, 'assets.mjs');
writeFileSync(assetsPath, assetsModule, 'utf8');
log(`assets module generated: ${Object.keys(assets).join(', ')} + catalog (${assetsModule.length} bytes) -> .deploy-tmp/assets.mjs`);

// 3. upload the script: main module + the lib modules it imports + generated assets
const moduleFiles = [
  ['worker.mjs', new URL('../worker.mjs', import.meta.url)],
  ['lib/paypal.js', new URL('../lib/paypal.js', import.meta.url)],
  ['lib/llm.js', new URL('../lib/llm.js', import.meta.url)],
  ['lib/agent.js', new URL('../lib/agent.js', import.meta.url)],
  ['lib/store.js', new URL('../lib/store.js', import.meta.url)],
  ['lib/mcp.js', new URL('../lib/mcp.js', import.meta.url)],
  ['assets.mjs', assetsModule], // generated above; string value = ready content
];
const bindings = [
  ...SECRETS.map((name) => ({ type: 'secret_text', name, text: env[name] })),
  { type: 'd1', name: 'DB', id: d1.uuid },
  // non-secret identifiers the worker may want at runtime; the deploy token
  // itself is deliberately NOT bound (the worker never calls the account API)
  { type: 'plain_text', name: 'WORKER_NAME', text: WORKER_NAME },
  { type: 'plain_text', name: 'CF_ACCOUNT_ID', text: acct },
];
const metadata = { main_module: 'worker.mjs', bindings, compatibility_date: '2025-01-01' };
const form = new FormData();
form.set('metadata', new Blob([JSON.stringify(metadata)], { type: 'application/json' }));
for (const [name, src] of moduleFiles) {
  const content = typeof src === 'string' ? src : readFileSync(src, 'utf8');
  form.append(name, new Blob([content], { type: 'application/javascript+module' }), name);
}
await api('PUT', `/accounts/${acct}/workers/scripts/${WORKER_NAME}`, form);
log(`worker script uploaded: ${WORKER_NAME} (${moduleFiles.length} modules; bindings: ${[...SECRETS, 'DB', 'WORKER_NAME', 'CF_ACCOUNT_ID'].join(', ')})`);

// 4. enable the workers.dev subdomain for this script only
const subdomainPath = `/accounts/${acct}/workers/scripts/${WORKER_NAME}/subdomain`;
try {
  await api('PUT', subdomainPath, { enabled: true, previews_enabled: false });
} catch (e) {
  if (!/405|method not allowed|not allowed/i.test(e.message)) throw e;
  await api('POST', subdomainPath, { enabled: true, previews_enabled: false }); // older API surface
}
log('workers.dev subdomain enabled');

// 5. verify: the judged URL answers /healthz with ok:true
const sub = await api('GET', `/accounts/${acct}/workers/subdomain`);
const healthz = `https://${WORKER_NAME}.${sub.subdomain}.workers.dev/healthz`;
let body = null;
for (let i = 0; i < 15; i++) {
  await new Promise((r) => setTimeout(r, 2000));
  try {
    const r = await fetch(healthz);
    body = await r.json().catch(() => null);
    if (body?.ok === true) break;
  } catch { /* propagation: retry */ }
  log(`waiting for ${healthz} (attempt ${i + 1})`);
}
if (body?.ok !== true) throw new Error(`healthz never returned ok:true at ${healthz} (last: ${JSON.stringify(body)})`);
console.log(`DEPLOY GREEN: ${healthz} -> ${JSON.stringify(body)}`);

function fileURLToPathSafe() {
  return decodeURIComponent(ROOT.pathname.replace(/^\/([A-Za-z]:)/, '$1'));
}
